[tool.poetry]
name = "python_hypermodern_python"
version = "0.1.0"
description = "The hypermodern Python project"
authors = ["algot <algot@ua.fm>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
